services:
  api:
    build:
      context: ./
    env_file:
      - .env
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./.conf/nginx:/etc/nginx/conf.d
    depends_on:
      - api

version: "3.7"
